[project]
name = "fastapi_simple_security"
version = "1.3.1"
description = "API key-based security for FastAPI"
authors = [
    {name = "mrtolkien", email = "gary.mialaret@gmail.com"},
    {name = "nicolaihs", email = "nhs@dsl.dk"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=5.0.0",
    "elasticsearch[async]>=8.0.0,<9.0.0",
    # 0.70 is needed to have the TestClient object
    "fastapi[standard]>=0.70",
    # Necessary as older versions don't work on python 3.10
    "urllib3>=1.26.12",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=22.3.0",
    "requests>=2.26.0",
    "pre-commit>=2.20.0",
    "pylint>=2.15.4",
    "isort>=5.10.1",
    "coverage>=6.5.0",
]

[project.urls]
Repository = "https://github.com/dsldk/fastapi_simple_security"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"

[tool.coverage.report]
omit = ["tests/conftest.py"]
